---
- name: Install Grafana
  shell: |
    cat <<EOF > /etc/yum.repos.d/grafana.repo
    [grafana]
    name=grafana
    baseurl=https://packages.grafana.com/oss/rpm
    repo_gpgcheck=1
    enabled=1
    gpgcheck=1
    gpgkey=https://packages.grafana.com/gpg.key
    EOF
    yum install -y grafana

- name: Enable and start Grafana
  shell: |
    systemctl enable grafana-server
    systemctl restart grafana-server
